spring.application.name=SpringRestApi
server.port = 9097


#Db Connection
spring.datasource.url=jdbc:mysql://localhost:3306/JAVAFSD_DB
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

#H2 Db Connection
#spring.datasource.url=jdbc:h2:mem:testdb  
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

